export * from "./DashboardPage/DashboardPage"
export * from "./DealPage/DealPage"
export * from "./FrontDeskPage/FrontDeskPage"
export * from "./GuestPage/GuestPage"
export * from "./RoomPage/RoomPage"
export * from "./RatePage/RatePage"
export * from "./LoginPage/LoginPage"
export * from "./SignupPage/SignupPage"
